print("How old are you?")
age = input()
print("How tall are you?")
height = input()
print("How much do you weight")
weight = input()
print("So, you're %s old, %s tall and %s heavy." % (age, height, weight))
